# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# The previous line enables IntelliSense for this file.
# See this post for more info https://www.meziantou.net/enabling-intellisense-for-github-actions-workflows-in-vs-code.htm

name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '6.x'
          includePrerelease: true
      # gitversion/execute step omitted for brevity
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
      - name: Display GitVersion variables (without prefix)
        run: |
          echo "Major: ${{ env.major }}"
          echo "Minor: ${{ env.minor }}"
          echo "Patch: ${{ env.patch }}"
          echo "PreReleaseTag: ${{ env.preReleaseTag }}"
          echo "PreReleaseTagWithDash: ${{ env.preReleaseTagWithDash }}"
          echo "PreReleaseLabel: ${{ env.preReleaseLabel }}"
          echo "PreReleaseNumber: ${{ env.preReleaseNumber }}"
          echo "WeightedPreReleaseNumber: ${{ env.weightedPreReleaseNumber }}"
          echo "BuildMetaData: ${{ env.buildMetaData }}"
          echo "BuildMetaDataPadded: ${{ env.buildMetaDataPadded }}"
          echo "FullBuildMetaData: ${{ env.fullBuildMetaData }}"
          echo "MajorMinorPatch: ${{ env.majorMinorPatch }}"
          echo "SemVer: ${{ env.semVer }}"
          echo "LegacySemVer: ${{ env.legacySemVer }}"
          echo "LegacySemVerPadded: ${{ env.legacySemVerPadded }}"
          echo "AssemblySemVer: ${{ env.assemblySemVer }}"
          echo "AssemblySemFileVer: ${{ env.assemblySemFileVer }}"
          echo "FullSemVer: ${{ env.fullSemVer }}"
          echo "InformationalVersion: ${{ env.informationalVersion }}"
          echo "BranchName: ${{ env.branchName }}"
          echo "EscapedBranchName: ${{ env.escapedBranchName }}"
          echo "Sha: ${{ env.sha }}"
          echo "ShortSha: ${{ env.shortSha }}"
          echo "NuGetVersionV2: ${{ env.nuGetVersionV2 }}"
          echo "NuGetVersion: ${{ env.nuGetVersion }}"
          echo "NuGetPreReleaseTagV2: ${{ env.nuGetPreReleaseTagV2 }}"
          echo "NuGetPreReleaseTag: ${{ env.nuGetPreReleaseTag }}"
          echo "VersionSourceSha: ${{ env.versionSourceSha }}"
          echo "CommitsSinceVersionSource: ${{ env.commitsSinceVersionSource }}"
          echo "CommitsSinceVersionSourcePadded: ${{ env.commitsSinceVersionSourcePadded }}"
          echo "UncommittedChanges: ${{ env.uncommittedChanges }}"
          echo "CommitDate: ${{ env.commitDate }}"
      - name: Display GitVersion variables (with prefix)
        run: |
          echo "Major: ${{ env.GitVersion_Major }}"
          echo "Minor: ${{ env.GitVersion_Minor }}"
          echo "Patch: ${{ env.GitVersion_Patch }}"
          echo "PreReleaseTag: ${{ env.GitVersion_PreReleaseTag }}"
          echo "PreReleaseTagWithDash: ${{ env.GitVersion_PreReleaseTagWithDash }}"
          echo "PreReleaseLabel: ${{ env.GitVersion_PreReleaseLabel }}"
          echo "PreReleaseNumber: ${{ env.GitVersion_PreReleaseNumber }}"
          echo "WeightedPreReleaseNumber: ${{ env.GitVersion_WeightedPreReleaseNumber }}"
          echo "BuildMetaData: ${{ env.GitVersion_BuildMetaData }}"
          echo "BuildMetaDataPadded: ${{ env.GitVersion_BuildMetaDataPadded }}"
          echo "FullBuildMetaData: ${{ env.GitVersion_FullBuildMetaData }}"
          echo "MajorMinorPatch: ${{ env.GitVersion_MajorMinorPatch }}"
          echo "SemVer: ${{ env.GitVersion_SemVer }}"
          echo "LegacySemVer: ${{ env.GitVersion_LegacySemVer }}"
          echo "LegacySemVerPadded: ${{ env.GitVersion_LegacySemVerPadded }}"
          echo "AssemblySemVer: ${{ env.GitVersion_AssemblySemVer }}"
          echo "AssemblySemFileVer: ${{ env.GitVersion_AssemblySemFileVer }}"
          echo "FullSemVer: ${{ env.GitVersion_FullSemVer }}"
          echo "InformationalVersion: ${{ env.GitVersion_InformationalVersion }}"
          echo "BranchName: ${{ env.GitVersion_BranchName }}"
          echo "EscapedBranchName: ${{ env.GitVersion_EscapedBranchName }}"
          echo "Sha: ${{ env.GitVersion_Sha }}"
          echo "ShortSha: ${{ env.GitVersion_ShortSha }}"
          echo "NuGetVersionV2: ${{ env.GitVersion_NuGetVersionV2 }}"
          echo "NuGetVersion: ${{ env.GitVersion_NuGetVersion }}"
          echo "NuGetPreReleaseTagV2: ${{ env.GitVersion_NuGetPreReleaseTagV2 }}"
          echo "NuGetPreReleaseTag: ${{ env.GitVersion_NuGetPreReleaseTag }}"
          echo "VersionSourceSha: ${{ env.GitVersion_VersionSourceSha }}"
          echo "CommitsSinceVersionSource: ${{ env.GitVersion_CommitsSinceVersionSource }}"
          echo "CommitsSinceVersionSourcePadded: ${{ env.GitVersion_CommitsSinceVersionSourcePadded }}"
          echo "UncommittedChanges: ${{ env.GitVersion_UncommittedChanges }}"
          echo "CommitDate: ${{ env.GitVersion_CommitDate }}"

  create_nuget:
    name: Create nuget
    runs-on: ubuntu-latest
    needs: [ calculate-version ]
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} -p:PackageVersion=${{ env.SEMVER }} -p:Version=${{ env.SEMVER }}
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg

  validate_nuget:
    name: Validate nuget metadata
    runs-on: ubuntu-latest
    needs: [ create_nuget ]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Install nuget validator
        run: dotnet tool update Meziantou.Framework.NuGetPackageValidation.Tool --global

      # Validate the NuGet package: https://www.nuget.org/packages/Meziantou.Framework.NuGetPackageValidation.Tool#readme-body-tab
      # If some rules are not applicable, you can disable them using the --excluded-rules or --excluded-rule-ids option
      - name: Validate package
        run: meziantou.validate-nuget-package (Get-ChildItem "${{ env.NuGetDirectory }}/*.nupkg")

  run_test:
    name: Run tests in solution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Run tests
      run: dotnet test --configuration Release

  deploy:
    name: Publish nuget packages to nuget.org
    # Publish only when creating a release
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ validate_nuget, run_test ]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ${{ env.NuGetDirectory }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
    - name: Publish NuGet package
      run: |
        foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json
        }